CREATE TABLE Clients (
    ClientID INT AUTO_INCREMENT PRIMARY KEY,
    Prenom VARCHAR(200) NOT NULL,
    Nom VARCHAR(200) NOT NULL,
    Email VARCHAR(200) NOT NULL,
    Mdp VARCHAR(200) NOT NULL,
    TelNum VARCHAR(12) NOT NULL,
    Adresse VARCHAR(200) NOT NULL,
    DateCreation TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Collection (
    CollectionID INT AUTO_INCREMENT PRIMARY KEY,
    NomCollection VARCHAR(200) NOT NULL
);

CREATE TABLE Produit (
    ProduitID int AUTO_INCREMENT PRIMARY KEY,
    Nom varchar(200) not null,
    TypeProduit varchar(200) not null,
    Marque varchar(200) not null,
    Taille varchar(10) not null,
    Prix DECIMAL (10,2) not null,
    CollectionID int not null,
    FOREIGN KEY (CollectionID) REFERENCES Collection(CollectionID)
);
ALTER TABLE Produit
ADD COLUMN Description VARCHAR(200) NOT NULL;

create table Panier( 
    PanierID int AUTO_INCREMENT PRIMARY KEY,
    ClientID int not null,
    ProduitID int not null,
    PrixTotal DECIMAL(10,2) not null,
    PromoCode varchar(10),
    FOREIGN KEY (ClientID) REFERENCES Clients(ClientID),
    FOREIGN KEY (ProduitID) REFERENCES Produit(ProduitID)
);
create table Commande (
    OrderID int AUTO_INCREMENT PRIMARY KEY,
    OrderDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PanierID int not null,
    Etat varchar(200) not null,
    FOREIGN KEY (PanierID) REFERENCES Panier(PanierID)
);
create table MethodePayement (
    ClientID int,
    CarteCredit int not null,
    CVC int not null,
    DateExpiration date not null,
    TypeDeCarte varchar(10) not null,
    FOREIGN KEY (ClientID) REFERENCES Clients(ClientID)
);
create table CodePromo (
    CodeID int AUTO_INCREMENT PRIMARY KEY,
    PourcentageRabais int not null,
    Expiration date not null
);

--les insert pour table collection




/*CREATE TABLE `PRODUIT` (
    `PRODUCTID` INT NOT NULL,
    `NAME` VARCHAR(200) NOT NULL,
    `TYPEPRODUIT` VARCHAR(200) NOT NULL,
    `MARQUE` VARCHAR(200) NOT NULL,
    `TAILLE` VARCHAR(10) NOT NULL,
    `PRICE` DECIMAL(10, 2) NOT NULL,
    `COLLECTIONID` INT NOT NULL,
    PRIMARY KEY (`PRODUCTID`),
    CONSTRAINT `UC_PRODUIT_NAME` UNIQUE (`NAME`)
);*/



/*CREATE TABLE `PANIER` (
    `PANIERID` INT NOT NULL,
    `CLIENTID` INT NOT NULL,
    `PRODUITID` INT NOT NULL,
    `PRIXTOTAL` DECIMAL(10, 2) NOT NULL,
    `PROMOCODE` VARCHAR(10),
    PRIMARY KEY (`PANIERID`)
);*/


/*
CREATE TABLE `COMMANDE` (
    `ORDERID` INT NOT NULL,
    `ORDERDATE` DATETIME NOT NULL,
    `PANIERID` INT NOT NULL,
    `ETAT` VARCHAR(200) NOT NULL,
    PRIMARY KEY ( `ORDERID` )
);*/


/*
CREATE TABLE `METHODEPAYEMENT` (
    `CLIENTID` INT NOT NULL,
    `CARTECREDIT` INT NOT NULL,
    `CVC` INT NOT NULL,
    `DATEEXPIRATION` INT NOT NULL,
    `TYPE` VARCHAR(10) NOT NULL
);*/


/*
CREATE TABLE `CODEPROMO` (
    `CODEID` VARCHAR(10) NOT NULL,
    `POURCENTAGERABAIS` INT NOT NULL,
    `EXPIRATION` DATETIME NOT NULL,
    PRIMARY KEY ( `CODEID` )
);*/

/*
ALTER TABLE `PRODUIT` ADD CONSTRAINT `FK_COMMANDE_COLECTIONID` FOREIGN KEY(`COLLECTIONID`) REFERENCES `COLLECTION` (`COLLECTIONID`);

ALTER TABLE `COMMANDE` ADD CONSTRAINT `FK_COMMANDE_PANIERID` FOREIGN KEY(`PANIERID`) REFERENCES `PANIER` (`PANIERID`);

ALTER TABLE `PANIER` ADD CONSTRAINT `FK_PANIER_CLIENTID` FOREIGN KEY(`CLIENTID`) REFERENCES `CLIENT` (`CLIENTID`);

ALTER TABLE `PANIER` ADD CONSTRAINT `FK_PANIER_PRODUITID` FOREIGN KEY(`PRODUITID`) REFERENCES `PRODUIT` (`PRODUCTID`);

ALTER TABLE `PANIER` ADD CONSTRAINT `FK_PANIER_PROMOCODE` FOREIGN KEY(`PROMOCODE`) REFERENCES `CODEPROMO` (`CODEID`);

ALTER TABLE `INVENTAIRE` ADD CONSTRAINT `FK_INVENTAIRE_PRODUCTID` FOREIGN KEY(`PRODUCTID`) REFERENCES `PRODUIT` (`PRODUCTID`);

ALTER TABLE `METHODEPAYEMENT` ADD CONSTRAINT `FK_METHODEPAYEMENT_CLIENTID` FOREIGN KEY(`CLIENTID`) REFERENCES `CLIENT` (`CLIENTID`);
*/