CREATE TABLE `CLIENT` (
    `CLIENTID` INT AUTO_INCREMENT,
    `PRENOM` VARCHAR(200) NOT NULL,
    `NOM` VARCHAR(200) NOT NULL,
    `EMAIL` VARCHAR(200) NOT NULL,
    `MDP` VARCHAR(200) NOT NULL,
    `TEL.NUM` VARCHAR(12) DEFAULT '000-000-0000' NOT NULL,
    `ADRESSE` VARCHAR(200) DEFAULT 'Adresse par défaut' NOT NULL,
    `DATECREATION` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (`CLIENTID`)
);

CREATE TABLE `COLLECTION` (
    `COLLECTIONID` INT AUTO_INCREMENT,
    `NOMCOLLECTION` VARCHAR(10) NOT NULL,
    PRIMARY KEY ( `COLLECTIONID` )
);

CREATE TABLE `PRODUIT` (
    `PRODUCTID` INT AUTO_INCREMENT,
    `NAME` VARCHAR(200) NOT NULL,
    `TYPEPRODUIT` VARCHAR(200) NOT NULL,
    `MARQUE` VARCHAR(200) NOT NULL,
    `TAILLE` VARCHAR(10) NOT NULL,
    `PRICE` DECIMAL(10, 2) NOT NULL,
    `COLLECTIONID` INT NOT NULL,
    PRIMARY KEY (`PRODUCTID`),
    CONSTRAINT `UC_PRODUIT_NAME` UNIQUE (`NAME`)
);

CREATE TABLE `PANIER` (
    `PANIERID` INT AUTO_INCREMENT,
    `CLIENTID` INT NOT NULL,
    `PRODUITID` INT NOT NULL,
    `PRIXTOTAL` DECIMAL(10, 2) NOT NULL,
    `PROMOCODE` VARCHAR(10),
    PRIMARY KEY (`PANIERID`)
);

CREATE TABLE `COMMANDE` (
    `ORDERID` INT AUTO_INCREMENT,
    `ORDERDATE` DATETIME NOT NULL,
    `PANIERID` INT NOT NULL,
    `ETAT` VARCHAR(200) NOT NULL,
    PRIMARY KEY ( `ORDERID` )
);

CREATE TABLE `METHODEPAYEMENT` (
    `CLIENTID` INT AUTO_INCREMENT,
    `CARTECREDIT` INT NOT NULL,
    `CVC` INT NOT NULL,
    `DATEEXPIRATION` INT NOT NULL,
    `TYPE` VARCHAR(10) NOT NULL
);

CREATE TABLE `CODEPROMO` (
    `CODEID` VARCHAR(10) AUTO_INCREMENT,
    `POURCENTAGERABAIS` INT NOT NULL,
    `EXPIRATION` DATETIME NOT NULL,
    PRIMARY KEY ( `CODEID` )
);


ALTER TABLE `PRODUIT` ADD CONSTRAINT `FK_COMMANDE_COLECTIONID` FOREIGN KEY(`COLLECTIONID`) REFERENCES `COLLECTION` (`COLLECTIONID`);

ALTER TABLE `COMMANDE` ADD CONSTRAINT `FK_COMMANDE_PANIERID` FOREIGN KEY(`PANIERID`) REFERENCES `PANIER` (`PANIERID`);

ALTER TABLE `PANIER` ADD CONSTRAINT `FK_PANIER_CLIENTID` FOREIGN KEY(`CLIENTID`) REFERENCES `CLIENT` (`CLIENTID`);

ALTER TABLE `PANIER` ADD CONSTRAINT `FK_PANIER_PRODUITID` FOREIGN KEY(`PRODUITID`) REFERENCES `PRODUIT` (`PRODUCTID`);

ALTER TABLE `PANIER` ADD CONSTRAINT `FK_PANIER_PROMOCODE` FOREIGN KEY(`PROMOCODE`) REFERENCES `CODEPROMO` (`CODEID`);

ALTER TABLE `INVENTAIRE` ADD CONSTRAINT `FK_INVENTAIRE_PRODUCTID` FOREIGN KEY(`PRODUCTID`) REFERENCES `PRODUIT` (`PRODUCTID`);

ALTER TABLE `METHODEPAYEMENT` ADD CONSTRAINT `FK_METHODEPAYEMENT_CLIENTID` FOREIGN KEY(`CLIENTID`) REFERENCES `CLIENT` (`CLIENTID`);
